package database;

// Generated Mar 21, 2014 4:30:53 PM by Hibernate Tools 4.0.0

/**
 * MenuList generated by hbm2java
 */
public class MenuList implements java.io.Serializable {

	private Integer menuId;
	private Integer restaurantId;
	private Integer mealSetHitCount;
	private Byte isNew;
	private String menuImagesPath;
	private String mealSetName;
	private String mealSetDescription;
	private Double mealSetPrice;
	private Double mealSetDiscount;

	public MenuList() {
	}

	public MenuList(Integer restaurantId, Integer mealSetHitCount, Byte isNew,
			String menuImagesPath, String mealSetName,
			String mealSetDescription, Double mealSetPrice,
			Double mealSetDiscount) {
		this.restaurantId = restaurantId;
		this.mealSetHitCount = mealSetHitCount;
		this.isNew = isNew;
		this.menuImagesPath = menuImagesPath;
		this.mealSetName = mealSetName;
		this.mealSetDescription = mealSetDescription;
		this.mealSetPrice = mealSetPrice;
		this.mealSetDiscount = mealSetDiscount;
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public Integer getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(Integer restaurantId) {
		this.restaurantId = restaurantId;
	}

	public Integer getMealSetHitCount() {
		return this.mealSetHitCount;
	}

	public void setMealSetHitCount(Integer mealSetHitCount) {
		this.mealSetHitCount = mealSetHitCount;
	}

	public Byte getIsNew() {
		return this.isNew;
	}

	public void setIsNew(Byte isNew) {
		this.isNew = isNew;
	}

	public String getMenuImagesPath() {
		return this.menuImagesPath;
	}

	public void setMenuImagesPath(String menuImagesPath) {
		this.menuImagesPath = menuImagesPath;
	}

	public String getMealSetName() {
		return this.mealSetName;
	}

	public void setMealSetName(String mealSetName) {
		this.mealSetName = mealSetName;
	}

	public String getMealSetDescription() {
		return this.mealSetDescription;
	}

	public void setMealSetDescription(String mealSetDescription) {
		this.mealSetDescription = mealSetDescription;
	}

	public Double getMealSetPrice() {
		return this.mealSetPrice;
	}

	public void setMealSetPrice(Double mealSetPrice) {
		this.mealSetPrice = mealSetPrice;
	}

	public Double getMealSetDiscount() {
		return this.mealSetDiscount;
	}

	public void setMealSetDiscount(Double mealSetDiscount) {
		this.mealSetDiscount = mealSetDiscount;
	}

}
