package database;

// Generated Mar 21, 2014 4:30:53 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PlaceOrder generated by hbm2java
 */
public class PlaceOrder implements java.io.Serializable {

	private Integer orderId;
	private Integer tableId;
	private Integer orderCount;
	private Date orderTime;
	private Date obsoleTime;
	private Integer userId;
	private String orderList;
	private Double prepaidAmount;
	private Double totalAmout;

	public PlaceOrder() {
	}

	public PlaceOrder(Integer tableId, Integer orderCount, Date orderTime,
			Date obsoleTime, Integer userId, String orderList,
			Double prepaidAmount, Double totalAmout) {
		this.tableId = tableId;
		this.orderCount = orderCount;
		this.orderTime = orderTime;
		this.obsoleTime = obsoleTime;
		this.userId = userId;
		this.orderList = orderList;
		this.prepaidAmount = prepaidAmount;
		this.totalAmout = totalAmout;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getTableId() {
		return this.tableId;
	}

	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	public Integer getOrderCount() {
		return this.orderCount;
	}

	public void setOrderCount(Integer orderCount) {
		this.orderCount = orderCount;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public Date getObsoleTime() {
		return this.obsoleTime;
	}

	public void setObsoleTime(Date obsoleTime) {
		this.obsoleTime = obsoleTime;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getOrderList() {
		return this.orderList;
	}

	public void setOrderList(String orderList) {
		this.orderList = orderList;
	}

	public Double getPrepaidAmount() {
		return this.prepaidAmount;
	}

	public void setPrepaidAmount(Double prepaidAmount) {
		this.prepaidAmount = prepaidAmount;
	}

	public Double getTotalAmout() {
		return this.totalAmout;
	}

	public void setTotalAmout(Double totalAmout) {
		this.totalAmout = totalAmout;
	}

}
