package database;

// Generated Mar 21, 2014 4:30:53 PM by Hibernate Tools 4.0.0

/**
 * RestaurantInformation generated by hbm2java
 */
public class RestaurantInformation implements java.io.Serializable {

	private Integer restaurantId;
	private Double restaurantLatitude;
	private Double restaurantLongitude;
	private String restaurantName;
	private String restaurantAddress;
	private String contactNumber1;
	private String contactNumber2;
	private String managerName;
	private String managerContact;

	public RestaurantInformation() {
	}

	public RestaurantInformation(Double restaurantLatitude,
			Double restaurantLongitude, String restaurantName,
			String restaurantAddress, String contactNumber1,
			String contactNumber2, String managerName, String managerContact) {
		this.restaurantLatitude = restaurantLatitude;
		this.restaurantLongitude = restaurantLongitude;
		this.restaurantName = restaurantName;
		this.restaurantAddress = restaurantAddress;
		this.contactNumber1 = contactNumber1;
		this.contactNumber2 = contactNumber2;
		this.managerName = managerName;
		this.managerContact = managerContact;
	}

	public Integer getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(Integer restaurantId) {
		this.restaurantId = restaurantId;
	}

	public Double getRestaurantLatitude() {
		return this.restaurantLatitude;
	}

	public void setRestaurantLatitude(Double restaurantLatitude) {
		this.restaurantLatitude = restaurantLatitude;
	}

	public Double getRestaurantLongitude() {
		return this.restaurantLongitude;
	}

	public void setRestaurantLongitude(Double restaurantLongitude) {
		this.restaurantLongitude = restaurantLongitude;
	}

	public String getRestaurantName() {
		return this.restaurantName;
	}

	public void setRestaurantName(String restaurantName) {
		this.restaurantName = restaurantName;
	}

	public String getRestaurantAddress() {
		return this.restaurantAddress;
	}

	public void setRestaurantAddress(String restaurantAddress) {
		this.restaurantAddress = restaurantAddress;
	}

	public String getContactNumber1() {
		return this.contactNumber1;
	}

	public void setContactNumber1(String contactNumber1) {
		this.contactNumber1 = contactNumber1;
	}

	public String getContactNumber2() {
		return this.contactNumber2;
	}

	public void setContactNumber2(String contactNumber2) {
		this.contactNumber2 = contactNumber2;
	}

	public String getManagerName() {
		return this.managerName;
	}

	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	public String getManagerContact() {
		return this.managerContact;
	}

	public void setManagerContact(String managerContact) {
		this.managerContact = managerContact;
	}

}
